(() => {
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={pending:'待处理',running:'分析中',succeeded:'有研究结果',no_signal:'无研究信号',failed:'失败',low_information:'低信息',anomaly:'异常',context_missing:'缺少上下文',restricted:'当前受限',source_limit:'超出本批数量上限'};
  const reasons={whitespace_or_encoding:'规范了空白或字符转义',source_too_long:'内容超过当前处理长度上限',empty_or_damaged:'空内容或编码损坏',reaction_only:'仅含表情或标点，保留反馈统计',context_dependent:'需要结合父评论或作品理解',contact_masked:'联系方式在外发时遮盖'};
  const errors={comment_daily_schema_missing:'每日研究尚未完成数据库升级，原声浏览仍可使用。',model_not_qualified:'请先在模型设置中完成测试并配置研究模型与额度。',model_revision_conflict:'设置已变化，请关闭后重新打开。',model_source_unavailable:'所选评论已有不可读或版本变化，请刷新后重选。',invalid_model_command:'请核对选择范围与额度。',model_database_unavailable:'研究服务暂不可用。'};
  const failures={model_input_limit:'作品上下文与单条评论超过输入额度，尚未调用模型',model_budget_overrun:'供应商报告用量超出单次额度',context_missing:'父评论与作品正文均未取得',source_limit:'保留在批次中，未进入本次数量额度',worker_interrupted:'执行中断，远端用量可能未知',json_or_schema_invalid:'输出结构不符合合同',missing_comment:'模型未返回这一条评论',quote_missing_or_ambiguous:'引用缺失或在原文中不唯一',quote_redacted_or_empty:'引用为空或包含遮盖内容',facets_or_evidence_invalid:'研究字段或引用不符合合同',provider_failed:'供应商未交付完整输出',provider_timeout:'供应商响应超时',context_changed:'调用期间上下文变化，结果未接纳',source_or_plan_unavailable:'来源受限或计划已暂停',model_disabled:'连接或计划已暂停'};
  const cleanLabels={direct:'可直接分析',context:'需要上下文',low_information:'低信息',anomaly:'异常'};
  const date=v=>v?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'未知';
  let overview=null,detailsGeneration=0;
  const dialog=document.createElement('dialog');dialog.className='lgi-research-dialog lgi-daily-dialog';document.body.append(dialog);
  const ask=async(path,body)=>{const r=await fetch('/api/local/comment-research/daily'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});const v=await r.json();if(!r.ok)throw new Error(errors[v.error]||'操作没有完成，请保留输入后重试。');return v;};
  function show(title,body){dialog.innerHTML=`<div class="lgi-research-dialog-heading"><h2>${esc(title)}</h2><button type="button" data-daily-close>关闭</button></div>${body}`;if(!dialog.open)dialog.showModal();}
  const loading=title=>show(title,'<p role="status">正在读取…</p>');
  const fail=e=>{const el=dialog.querySelector('[data-form-error]');if(el)el.textContent=e.message;else show('未完成',`<p role="alert">${esc(e.message)}</p>`);};
  const api={onRefresh:()=>{}};
  api.cleaningHtml=p=>`<section><h3>清洗处理</h3>${p?.cleanState?`<p>${esc(cleanLabels[p.cleanState])} · ${esc((p.cleaning?.reasons||[]).map(r=>reasons[r]||'规则处理').join('；')||'保留原始表达')}</p><details><summary>查看规范后的文本</summary><blockquote>${esc(p.cleaning?.text||'没有可分析文本')}</blockquote></details><p class="lgi-research-meta">原文完整保留，外发模型时另行遮盖可识别联系方式。</p>`:'<p>尚未清洗，不影响阅读与人工收存。</p>'}</section>`;
  api.mediaHtml=items=>`<details><summary>已有媒体文字</summary>${(items||[]).length?(items||[]).map(v=>`<p>${esc(({ocr_text:'图片文字',frame_ocr_text:'视频画面文字',asr_text:'视频转录'})[v.kind]||'媒体文字')} · ${v.state==='ACQUIRED'?'已取得':'尚不可用'}</p>${v.displayText?`<blockquote>${esc(v.displayText)}</blockquote>`:''}`).join(''):'<p>尚未取得 OCR 或转录文字。可从来源作品查看已有媒体。</p>'}</details>`;
  api.render=data=>{
    overview=data;
    document.getElementById('result-count').textContent=`最近 ${data.items.length} 批 · 北京时间`;
    document.getElementById('results').innerHTML=`<p class="lgi-research-meta">每日研究${data.schedule.enabled?'已启用':'未启用或已暂停'}${data.schedule.next_end?' · 下一个待封存截点 '+esc(date(data.schedule.next_end)):''}。数字只描述本机观察样本，低信息与异常仍保留。重试失败会占用本批剩余额度，未知用量预留不释放。</p>`+(data.items.length?`<table><thead><tr><th>研究批次</th><th>材料范围</th><th>处理进展</th><th>额度使用</th><th>操作</th></tr></thead><tbody>${data.items.map(b=>`<tr><td>${b.kind==='daily'?'每日新增':'指定样本'}<div class="lgi-research-meta">${esc(date(b.start))}—${esc(date(b.end))}</div></td><td>${b.total.toLocaleString()} 条<div class="lgi-research-meta">${b.works.toLocaleString()} 篇当前可读作品</div></td><td>${Object.entries(b.counts).map(([k,n])=>`${esc(labels[k]||k)} ${n}`).join(' · ')||'没有新增评论'}${!b.enabled?'<div class="lgi-research-meta">批次已暂停</div>':''}<div class="lgi-research-meta">${Object.entries(b.cleaning||{}).map(([k,n])=>esc(cleanLabels[k]||'待清洗')+' '+n).join(' · ')}</div>${b.counts.pending&&b.tokenLimit-b.chargedTokens<b.nextReservation?'<div class="lgi-research-meta">剩余额度不足以预留下一包</div>':''}</td><td>${b.chargedTokens.toLocaleString()} / ${b.tokenLimit.toLocaleString()}<div class="lgi-research-meta">Token · 含用量未知时的预留</div></td><td><button type="button" data-batch="${b.batchRef}">查看</button><button type="button" data-batch-toggle="${b.batchRef}" data-enabled="${!b.enabled}">${b.enabled?'暂停':'恢复'}</button>${b.counts.failed?`<button type="button" data-batch-retry="${b.batchRef}" data-command="${crypto.randomUUID()}" ${b.enabled?'':'disabled'}>重试失败</button>`:''}</td></tr>`).join('')}</tbody></table>`:'<p class="lgi-research-empty">还没有研究批次。先在原声浏览中勾选少量评论试跑，确认效果后启用每日研究。</p>');
  };
  async function modelSettings(){const r=await fetch('/api/local/model-settings',{cache:'no-store'});if(!r.ok)throw new Error('模型设置暂不可读。');return r.json();}
  function modelSummary(m){if(!m.model?.modelConnected)return '<p>'+esc(({NEEDS_SELECTION:'已有模型通过校验，请选择并保存默认模型。',NEEDS_QUALIFICATION:'请在供应商弹窗中保存并测试评论格式，测试无需先设置默认模型。',PAUSED:'模型连接已暂停，请先启用。'})[m.model?.modelState]||'请添加供应商并完成测试，再选择默认模型。')+' <a href="/settings/models">前往模型设置</a></p>';const model=(m.models||[]).find(v=>v.modelRef===m.config.modelRef);return `<p>研究模型：${esc(model?.modelId||'当前冻结配置')} · ${esc(model?.connectionName||'已配置供应商')}。所选评论、父评论与作品已有文字会经清洗及联系方式遮盖后发送。</p>`;}
  api.openSelected=async refs=>{loading('分析所选评论');try{const m=await modelSettings();const id=crypto.randomUUID();show('分析所选评论',`${modelSummary(m)}<p>选中 ${refs.length} 条评论。按所属作品分包；不增加采集。</p>${m.config?'<form data-daily-selected><label>本批 Token 总上限<input name="tokens" type="number" min="1024" max="10000000" value="100000" required></label><p data-form-error role="status"></p><button type="submit">确认范围并开始分析</button></form>':''}`);dialog.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await ask('/selected',{batchRef:id,configRef:m.config.configRef,sourceRefs:refs,tokenLimit:Number(new FormData(e.target).get('tokens'))});dialog.close();document.getElementById('research-detail').close();api.onRefresh(true);}catch(err){fail(err);}finally{b.disabled=false;}});}catch(e){fail(e);}};
  api.openSettings=async()=>{loading('每日研究设置');try{const [data,m]=await Promise.all([ask(''),modelSettings()]);const s=data.schedule;show('每日研究设置',`${modelSummary(m)}<p>北京时间 23:00 固定批次。首次启用从启用时刻开始；暂停期间不调用，恢复后按原截点补建批次。每批有独立额度。</p>${m.config?`<form data-daily-settings><label>每日自动研究<select name="enabled"><option value="false">暂停</option><option value="true" ${s.enabled?'selected':''}>启用</option></select></label><label>每批最多分析评论数<input name="sources" type="number" min="1" max="1000" value="${s.source_limit}" required></label><label>每批 Token 总上限<input name="tokens" type="number" min="1024" max="10000000" value="${s.token_limit}" required></label><p class="lgi-research-meta">来源清单与超额条目保留。启用每日研究后，原先即时自动处理计划暂停，避免重复调用。</p><p data-form-error role="status"></p><button type="submit">保存研究设置</button></form>`:''}`);dialog.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;const f=new FormData(e.target);try{await ask('/schedule',{expectedRevision:s.revision,enabled:f.get('enabled')==='true',configRef:m.config.configRef,sourceLimit:Number(f.get('sources')),tokenLimit:Number(f.get('tokens'))});dialog.close();api.onRefresh();}catch(err){fail(err);}finally{b.disabled=false;}});}catch(e){fail(e);}};
  async function showBatch(ref,after=null){const generation=++detailsGeneration;loading('批次处理明细');try{const data=await ask('/'+ref+(after?'?after='+after:''));if(generation!==detailsGeneration||!dialog.open)return;show('批次处理明细',`<p>逐条核对原声与分析。当前页最多 50 条；研究结果为候选解释。</p><table><thead><tr><th>评论</th><th>状态与原因</th><th>研究结果</th></tr></thead><tbody>${data.items.map(i=>`<tr><td><button type="button" class="lgi-voice-open" data-source="${i.sourceRef}"><span class="lgi-voice-preview">${esc(i.body||'来源当前受限')}</span></button></td><td>${esc(labels[i.state]||i.state)}<div class="lgi-research-meta">${esc(failures[i.failureCode]||i.failureCode||'')}</div></td><td>${i.analysis?(i.analysis.spans||[]).flatMap(s=>s.facets).map(f=>`<div>${esc(f.label)} <span class="lgi-research-meta">${f.basis==='explicit'?'直接表达':'推断'}</span></div>`).join('')||'未提取到研究信号':'尚无可展示结果'}</td></tr>`).join('')}</tbody></table>${data.nextCursor?`<button type="button" data-batch-next="${ref}" data-after="${data.nextCursor}">下一页</button>`:''}`);}catch(e){if(generation===detailsGeneration)fail(e);}}
  document.addEventListener('click',async e=>{const one=e.target.closest('[data-daily-source]');if(one){api.openSelected([one.dataset.dailySource]);return;}const close=e.target.closest('[data-daily-close]');if(close){dialog.close();return;}const retry=e.target.closest('[data-batch-retry]');if(retry){retry.disabled=true;try{const r=await ask('/'+retry.dataset.batchRetry+'/retry',{commandRef:retry.dataset.command});await api.onRefresh();document.getElementById('feedback').textContent='已重新排队 '+r.queued+' 条；仍受原批次次数与剩余额度限制，未知用量预留保留。';}catch(err){document.getElementById('feedback').textContent=err.message;}finally{retry.disabled=false;}return;}const b=e.target.closest('[data-batch]');if(b){showBatch(b.dataset.batch);return;}const next=e.target.closest('[data-batch-next]');if(next){showBatch(next.dataset.batchNext,next.dataset.after);return;}const toggle=e.target.closest('[data-batch-toggle]');if(toggle){toggle.disabled=true;try{await ask('/'+toggle.dataset.batchToggle,{enabled:toggle.dataset.enabled==='true'});api.onRefresh();}catch(err){document.getElementById('feedback').textContent=err.message;}finally{toggle.disabled=false;}}});
  dialog.addEventListener('close',()=>{detailsGeneration++;dialog.replaceChildren();});
  window.CommentDaily=api;
})();
