#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$project_root"

usage() {
  cat >&2 <<'EOF'
usage: ./scripts/init-comment-study.sh [--database disposable_proof_database]

Initialize the clean Comment Study base schema once, only when no Comment Study tables exist.
The optional database form is reserved for an exact disposable runtime proof database.
EOF
}

database_name=""
if [[ "${1:-}" == "--database" ]]; then
  database_name="${2:-}"
  shift 2
  if [[ ! "$database_name" =~ ^linggan_intelligence_runtime_proof_[0-9a-f]+$ ]]; then
    echo "--database only accepts an exact disposable runtime proof database name" >&2
    exit 1
  fi
fi
if [[ $# -ne 0 ]]; then
  usage
  exit 1
fi

"$project_root/scripts/setup-local-env.sh" >/dev/null
set -a
# shellcheck disable=SC1091
source "$project_root/.env"
set +a

if [[ "${POSTGRES_PASSWORD:-}" == replace-* || "${#POSTGRES_PASSWORD}" -lt 24 ]]; then
  echo "POSTGRES_PASSWORD must be a non-placeholder local secret with at least 24 characters" >&2
  exit 1
fi
if [[ "${POSTGRES_USER:-}" != "linggan_dev_admin" || -z "${POSTGRES_DB:-}" ]]; then
  echo "local environment must use linggan_dev_admin and POSTGRES_DB" >&2
  exit 1
fi
if [[ ! "${POSTGRES_PORT:-}" =~ ^[1-9][0-9]{0,4}$ ]] || (( POSTGRES_PORT > 65535 )); then
  echo "POSTGRES_PORT must be a valid local TCP port" >&2
  exit 1
fi
database_name="${database_name:-$POSTGRES_DB}"

"$project_root/scripts/dev-db.sh" up >/dev/null
published_address="$(docker compose port postgres 5432)"
if [[ "$published_address" != "127.0.0.1:${POSTGRES_PORT}" ]]; then
  echo "the Compose PostgreSQL port does not match the local runtime target; refusing to continue" >&2
  exit 1
fi
if ! printf '%s\n' "$POSTGRES_PASSWORD" | docker compose run --rm --no-deps -T postgres \
  sh -ceu '
    IFS= read -r database_password
    case "$database_password" in
      ""|*[!0-9a-f]*)
        echo "POSTGRES_PASSWORD must be the hex local secret generated by setup-local-env.sh" >&2
        exit 1
        ;;
    esac
    PGPASSWORD="$database_password" exec psql -X -v ON_ERROR_STOP=1 -h postgres \
      -U linggan_dev_admin -d "$1" -c "SELECT 1;"
  ' sh "$database_name" >/dev/null; then
  echo "the local database role does not accept the current .env password; no schema was changed" >&2
  exit 1
fi

if [[ "$database_name" == "$POSTGRES_DB" ]]; then
  launchctl_result=""
  if ! command -v launchctl >/dev/null 2>&1; then
    echo "cannot verify local runtime services are stopped; refusing clean Comment Study initialization" >&2
    exit 1
  fi
  for label in com.linggan-intelligence.local-runtime \
    com.linggan-intelligence.patrol-worker com.linggan-intelligence.media-worker; do
    if launchctl_result="$(launchctl print "gui/$(id -u)/$label" 2>&1)"; then
      echo "${label} must be stopped before first-time Comment Study initialization" >&2
      exit 1
    fi
    if [[ "$launchctl_result" != *"Could not find service \"$label\" "* ]]; then
      echo "cannot confirm $label is stopped; refusing first-time Comment Study initialization" >&2
      echo "$launchctl_result" >&2
      exit 1
    fi
  done
  for process in linggan-api linggan-worker linggan-media-worker; do
    if pgrep -x "$process" >/dev/null 2>&1; then
      echo "${process} is still running; refusing first-time Comment Study initialization" >&2
      exit 1
    fi
  done
  if lsof -nP -iTCP:3000 -sTCP:LISTEN >/dev/null 2>&1; then
    echo "port 3000 is still serving; refusing first-time Comment Study initialization" >&2
    exit 1
  fi
fi

base_schema_ready="$(docker compose exec -T postgres psql -X -v ON_ERROR_STOP=1 -At \
  -U "$POSTGRES_USER" -d "$database_name" <<'SQL'
SELECT (to_regclass('observation_domain') IS NOT NULL
    AND to_regclass('linggan_material_content') IS NOT NULL
    AND to_regclass('linggan_material_comment') IS NOT NULL
    AND to_regclass('linggan_model_config') IS NOT NULL
    AND to_regclass('linggan_model_invocation') IS NOT NULL
    AND to_regprocedure('scope_001_now()') IS NOT NULL
    AND EXISTS (SELECT 1 FROM pg_type type
                JOIN pg_namespace namespace ON namespace.oid=type.typnamespace
                WHERE namespace.nspname='public' AND type.typname='vector'));
SQL
)"
if [[ "$base_schema_ready" != "t" ]]; then
  echo "retained material, model, domain, clock, or vector schema is incomplete; refusing bootstrap" >&2
  exit 1
fi

comment_study_table_count="$(docker compose exec -T postgres psql -X -v ON_ERROR_STOP=1 -At \
  -U "$POSTGRES_USER" -d "$database_name" \
  -c "SELECT count(*) FROM information_schema.tables WHERE table_schema=current_schema() AND table_name LIKE 'linggan_comment_study_%';")"
if [[ "$comment_study_table_count" != "0" ]]; then
  echo "Comment Study tables already exist or are partial; refusing bootstrap and preserving the database" >&2
  exit 1
fi

running_invocations="$(docker compose exec -T postgres psql -X -v ON_ERROR_STOP=1 -At \
  -U "$POSTGRES_USER" -d "$database_name" \
  -c "SELECT count(*) FROM linggan_model_invocation WHERE state='running';")"
if [[ "$running_invocations" != "0" ]]; then
  echo "running model invocations must settle before first-time Comment Study initialization" >&2
  exit 1
fi

{
  printf 'BEGIN;\n'
  cat "$project_root/database/bootstrap/comment-study-001.sql"
  printf 'COMMIT;\n'
} | docker compose exec -T postgres psql -X -v ON_ERROR_STOP=1 \
  -U "$POSTGRES_USER" -d "$database_name" >/dev/null

echo "clean Comment Study base schema initialized; no legacy data was read, converted, or reset"
