#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$project_root"

usage() {
  cat >&2 <<'EOF'
usage: ./scripts/local-runtime.sh {migrate|repair-password|serve} [--database database_name]

  migrate          apply the approved local Linggan migrations exactly once
  repair-password  explicitly align the local persistent database role with .env
  serve            migrate, then start the API, scheduler and local media processor

The optional --database form is reserved for an exact, disposable runtime proof
database. It refuses every name except linggan_intelligence_runtime_proof_<hex>.
EOF
}

ensure_env() {
  "$project_root/scripts/setup-local-env.sh" >/dev/null
  set -a
  # shellcheck disable=SC1091
  source "$project_root/.env"
  set +a

  if [[ "${POSTGRES_PASSWORD:-}" == replace-* || "${#POSTGRES_PASSWORD}" -lt 24 ]]; then
    echo "POSTGRES_PASSWORD must be a non-placeholder local secret with at least 24 characters" >&2
    exit 1
  fi

  if [[ "${POSTGRES_USER:-}" != "linggan_dev_admin" || -z "${POSTGRES_DB:-}" ]]; then
    echo "local environment must use linggan_dev_admin and POSTGRES_DB" >&2
    exit 1
  fi

  if [[ ! "${POSTGRES_PORT:-}" =~ ^[1-9][0-9]{0,4}$ ]] || (( POSTGRES_PORT > 65535 )); then
    echo "POSTGRES_PORT must be a valid local TCP port" >&2
    exit 1
  fi
}

database_name=""
if [[ "${1:-}" == "--database" ]]; then
  database_name="${2:-}"
  shift 2
  if [[ ! "$database_name" =~ ^linggan_intelligence_runtime_proof_[0-9a-f]+$ ]]; then
    echo "--database only accepts an exact disposable runtime proof database name" >&2
    exit 1
  fi
fi

if [[ $# -ne 1 ]]; then
  usage
  exit 1
fi
command_name="$1"

psql_in_container() {
  docker compose exec -T postgres psql -X -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$database_name" "$@"
}

local_database_url() {
  # POSTGRES_PASSWORD is generated as hex and POSTGRES_USER is fixed, so neither needs URL
  # escaping. This is intentionally derived from the exact Compose target; DATABASE_ADMIN_URL
  # is not an authority for the runtime target and must never redirect the API after migration.
  printf 'postgresql://%s:%s@127.0.0.1:%s/%s' \
    "$POSTGRES_USER" "$POSTGRES_PASSWORD" "$POSTGRES_PORT" "$database_name"
}

bind_runtime_database_target() {
  local derived_url
  derived_url="$(local_database_url)"
  if [[ -n "${LINGGAN_LOCAL_DATABASE_URL:-}" && "$LINGGAN_LOCAL_DATABASE_URL" != "$derived_url" ]]; then
    echo "LINGGAN_LOCAL_DATABASE_URL conflicts with the exact database verified by migration; refusing to start" >&2
    exit 1
  fi
  export LINGGAN_LOCAL_DATABASE_URL="$derived_url"
}

verify_runtime_port_binding() {
  local published_address
  published_address="$(docker compose port postgres 5432)"
  if [[ "$published_address" != "127.0.0.1:${POSTGRES_PORT}" ]]; then
    echo "the Compose PostgreSQL port does not match the local runtime target; refusing to continue" >&2
    exit 1
  fi
}

verify_application_database_credentials() {
  # The database container's loopback hba rule is trust-based. Verify through
  # a separate Compose client on the database network instead, so this proves
  # the password works for the application connection path. The current .env
  # secret travels only on stdin: it must never become a Docker CLI argument.
  if ! printf '%s\n' "$POSTGRES_PASSWORD" | docker compose run --rm --no-deps -T postgres \
    sh -ceu '
      IFS= read -r database_password
      case "$database_password" in
        ""|*[!0-9a-f]*)
          echo "POSTGRES_PASSWORD must be the hex local secret generated by setup-local-env.sh" >&2
          exit 1
          ;;
      esac
      PGPASSWORD="$database_password" exec psql -X -v ON_ERROR_STOP=1 -h postgres \
        -U linggan_dev_admin -d "$1" -c "SELECT 1;"
    ' sh "$database_name" >/dev/null; then
    echo "the local database role does not accept the current .env password; no data was changed" >&2
    echo "run ./scripts/local-runtime.sh repair-password to explicitly align this local-only role, then retry" >&2
    exit 1
  fi
}

repair_password() {
  "$project_root/scripts/dev-db.sh" up >/dev/null
  # The container may have been created with an older secret. Pass the value
  # just verified from this invocation's .env over stdin; never select the
  # container's startup environment as the repair authority or place it in a
  # Docker CLI argument.
  printf '%s\n' "$POSTGRES_PASSWORD" | docker compose exec -T postgres sh -ceu '
    IFS= read -r repair_password
    case "$repair_password" in
      ""|*[!0-9a-f]*)
        echo "POSTGRES_PASSWORD must be the hex local secret generated by setup-local-env.sh" >&2
        exit 1
        ;;
    esac
    printf "ALTER ROLE linggan_dev_admin PASSWORD '\''%s'\'';\\n" "$repair_password" \
      | psql -X -v ON_ERROR_STOP=1 -U linggan_dev_admin -d postgres >/dev/null
  '
  verify_application_database_credentials
  echo "local database role password aligned with the existing .env; persisted data was not reset or removed"
}

ensure_migration_ledger() {
  docker compose exec -T postgres psql -X -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$database_name" >/dev/null <<'SQL'
    CREATE TABLE IF NOT EXISTS linggan_local_schema_migration (
      migration_id text PRIMARY KEY,
      migration_sha256 text NOT NULL CHECK (migration_sha256 ~ '^[0-9a-f]{64}$'),
      applied_at timestamptz NOT NULL DEFAULT clock_timestamp()
    );
SQL
}

apply_migration_once() {
  local migration_id="$1"
  local migration_path="$2"
  local expected_hash existing_hash
  expected_hash="$(shasum -a 256 "$migration_path" | awk '{print $1}')"
  existing_hash="$(psql_in_container -At -c "SELECT migration_sha256 FROM linggan_local_schema_migration WHERE migration_id = '${migration_id}'")"

  if [[ -n "$existing_hash" ]]; then
    if [[ "$existing_hash" != "$expected_hash" ]]; then
      echo "migration ${migration_id} was previously applied with a different checksum; refusing to continue" >&2
      exit 1
    fi
    echo "migration ${migration_id} already recorded"
    return
  fi

  {
    printf 'BEGIN;\n'
    cat "$migration_path"
    printf "INSERT INTO linggan_local_schema_migration (migration_id, migration_sha256) VALUES ('%s', '%s');\n" "$migration_id" "$expected_hash"
    printf 'COMMIT;\n'
  } | psql_in_container >/dev/null
  echo "migration ${migration_id} applied"
}

migrate() {
  "$project_root/scripts/dev-db.sh" up >/dev/null
  verify_runtime_port_binding
  verify_application_database_credentials
  ensure_migration_ledger
  apply_migration_once "0001_scope_001_capture_evidence" "$project_root/database/migrations/0001_scope_001_capture_evidence.sql"
  apply_migration_once "0002_local_001_discovery" "$project_root/database/migrations/0002_local_001_discovery.sql"
  apply_migration_once "0003_local_trusted_producer" "$project_root/database/migrations/0003_local_trusted_producer.sql"
  apply_migration_once "0004_plugin_runtime_all_capabilities" "$project_root/database/migrations/0004_plugin_runtime_all_capabilities.sql"
  apply_migration_once "0005_collection_observation_target" "$project_root/database/migrations/0005_collection_observation_target.sql"
  apply_migration_once "0006_collection_acquisition_chain" "$project_root/database/migrations/0006_collection_acquisition_chain.sql"
  apply_migration_once "0007_execution_station" "$project_root/database/migrations/0007_execution_station.sql"
  apply_migration_once "0008_collection_risk_pause" "$project_root/database/migrations/0008_collection_risk_pause.sql"
  apply_migration_once "0009_work_order_station" "$project_root/database/migrations/0009_work_order_station.sql"
  apply_migration_once "0010_work_order_lease" "$project_root/database/migrations/0010_work_order_lease.sql"
  apply_migration_once "0011_execution_gate" "$project_root/database/migrations/0011_execution_gate.sql"
  apply_migration_once "0012_target_monitor_schedule" "$project_root/database/migrations/0012_target_monitor_schedule.sql"
  apply_migration_once "0013_drop_execution_gate" "$project_root/database/migrations/0013_drop_execution_gate.sql"
  apply_migration_once "0014_target_group" "$project_root/database/migrations/0014_target_group.sql"
  apply_migration_once "0015_material_projection" "$project_root/database/migrations/0015_material_projection.sql"
  apply_migration_once "0016_material_social_lanes" "$project_root/database/migrations/0016_material_social_lanes.sql"
  apply_migration_once "0017_material_media_projection" "$project_root/database/migrations/0017_material_media_projection.sql"
  apply_migration_once "0018_material_discovery_lane" "$project_root/database/migrations/0018_material_discovery_lane.sql"
  apply_migration_once "0019_work_order_lease_task_sequence" "$project_root/database/migrations/0019_work_order_lease_task_sequence.sql"
  apply_migration_once "0020_observation_runtime_automation" "$project_root/database/migrations/0020_observation_runtime_automation.sql"
  apply_migration_once "0021_discovery_cover_media_acquisition" "$project_root/database/migrations/0021_discovery_cover_media_acquisition.sql"
  apply_migration_once "0022_material_deepening_scope" "$project_root/database/migrations/0022_material_deepening_scope.sql"
  apply_migration_once "0023_material_engagement_and_media_components" "$project_root/database/migrations/0023_material_engagement_and_media_components.sql"
  apply_migration_once "0024_media_processing_runtime" "$project_root/database/migrations/0024_media_processing_runtime.sql"
  apply_migration_once "0025_comment_current_projection" "$project_root/database/migrations/0025_comment_current_projection.sql"
  apply_migration_once "0026_work_resource_read" "$project_root/database/migrations/0026_work_resource_read.sql"
  apply_migration_once "0027_unified_media_resource" "$project_root/database/migrations/0027_unified_media_resource.sql"
  apply_migration_once "0029_author_avatar_media" "$project_root/database/migrations/0029_author_avatar_media.sql"
  apply_migration_once "0030_comment_image_media" "$project_root/database/migrations/0030_comment_image_media.sql"
  apply_migration_once "0031_topic_workspace" "$project_root/database/migrations/0031_topic_workspace.sql"
  apply_migration_once "0032_author_profile_avatar_media" "$project_root/database/migrations/0032_author_profile_avatar_media.sql"
  apply_migration_once "0033_dispatch_failure_recovery" "$project_root/database/migrations/0033_dispatch_failure_recovery.sql"
  apply_migration_once "0034_collection_control_closure" "$project_root/database/migrations/0034_collection_control_closure.sql"
  apply_migration_once "0035_claimed_station_auto_acceptance" "$project_root/database/migrations/0035_claimed_station_auto_acceptance.sql"
  apply_migration_once "0036_monitor_scheduling_clarity" "$project_root/database/migrations/0036_monitor_scheduling_clarity.sql"
  apply_migration_once "0037_collection_scheduler_scale" "$project_root/database/migrations/0037_collection_scheduler_scale.sql"
  apply_migration_once "0038_detail_only_material_scope" "$project_root/database/migrations/0038_detail_only_material_scope.sql"
  apply_migration_once "0039_comment_research" "$project_root/database/migrations/0039_comment_research.sql"
  apply_migration_once "0040_model_pi" "$project_root/database/migrations/0040_model_pi.sql"
  apply_migration_once "0041_observation_domain" "$project_root/database/migrations/0041_observation_domain.sql"
  apply_migration_once "0042_keyword_monitoring_lifecycle" "$project_root/database/migrations/0042_keyword_monitoring_lifecycle.sql"
  apply_migration_once "0043_comment_daily" "$project_root/database/migrations/0043_comment_daily.sql"
  apply_migration_once "0044_cross_industry_comment" "$project_root/database/migrations/0044_cross_industry_comment.sql"
  apply_migration_once "0045_deep_archive_recovery" "$project_root/database/migrations/0045_deep_archive_recovery.sql"
  apply_migration_once "0046_keyword_sampling_policy" "$project_root/database/migrations/0046_keyword_sampling_policy.sql"
  apply_migration_once "0047_collection_detail_failure_boundary" "$project_root/database/migrations/0047_collection_detail_failure_boundary.sql"
  apply_migration_once "0048_comment_intelligence" "$project_root/database/migrations/0048_comment_intelligence.sql"
  apply_migration_once "0049_comment_research_runtime" "$project_root/database/migrations/0049_comment_research_runtime.sql"
  apply_migration_once "0050_comment_research_automation" "$project_root/database/migrations/0050_comment_research_automation.sql"
  apply_migration_once "0051_comment_problem_vectors" "$project_root/database/migrations/0051_comment_problem_vectors.sql"
  apply_migration_once "0052_work_order_expiry" "$project_root/database/migrations/0052_work_order_expiry.sql"
  apply_migration_once "0053_comment_research_rules" "$project_root/database/migrations/0053_comment_research_rules.sql"
  apply_migration_once "0054_comment_auto_policy" "$project_root/database/migrations/0054_comment_auto_policy.sql"
  apply_migration_once "0055_comment_research_replay" "$project_root/database/migrations/0055_comment_research_replay.sql"
  apply_migration_once "0056_comment_semantic_atoms" "$project_root/database/migrations/0056_comment_semantic_atoms.sql"
  apply_migration_once "0057_comment_local_recovery" "$project_root/database/migrations/0057_comment_local_recovery.sql"
  apply_migration_once "0058_comment_field_repair" "$project_root/database/migrations/0058_comment_field_repair.sql"
  apply_migration_once "0059_comment_replay_continuity" "$project_root/database/migrations/0059_comment_replay_continuity.sql"
  apply_migration_once "0060_comment_topic_associations" "$project_root/database/migrations/0060_comment_topic_associations.sql"
  apply_migration_once "0061_material_retirement" "$project_root/database/migrations/0061_material_retirement.sql"
  apply_migration_once "0062_human_moment" "$project_root/database/migrations/0062_human_moment.sql"
  apply_migration_once "0063_content_author_attribution" "$project_root/database/migrations/0063_content_author_attribution.sql"
  apply_migration_once "0064_account_observation_normalization" "$project_root/database/migrations/0064_account_observation_normalization.sql"
  apply_migration_once "0064_comment_research_kernel" "$project_root/database/migrations/0064_comment_research_kernel.sql"
  apply_migration_once "0065_comment_research_vector_candidates" "$project_root/database/migrations/0065_comment_research_vector_candidates.sql"
  apply_migration_once "0066_comment_research_change_signals" "$project_root/database/migrations/0066_comment_research_change_signals.sql"
  apply_migration_once "0067_comment_research_run_item_lease" "$project_root/database/migrations/0067_comment_research_run_item_lease.sql"
  apply_migration_once "0068_comment_research_problem_resolution" "$project_root/database/migrations/0068_comment_research_problem_resolution.sql"
  apply_migration_once "0069_comment_research_v1_cutover" "$project_root/database/migrations/0069_comment_research_v1_cutover.sql"
  apply_migration_once "0070_comment_research_v1_derivation_head" "$project_root/database/migrations/0070_comment_research_v1_derivation_head.sql"
  apply_migration_once "0071_cross_industry_sampling_provenance" "$project_root/database/migrations/0071_cross_industry_sampling_provenance.sql"
  apply_migration_once "0072_cross_industry_sample_lane" "$project_root/database/migrations/0072_cross_industry_sample_lane.sql"
  apply_migration_once "0073_cross_industry_sample_observation" "$project_root/database/migrations/0073_cross_industry_sample_observation.sql"
  apply_migration_once "0074_cross_industry_detail_scope" "$project_root/database/migrations/0074_cross_industry_detail_scope.sql"
  apply_migration_once "0075_local_embedding_001" "$project_root/database/migrations/0075_local_embedding_001.sql"
  apply_migration_once "0076_monitor_rule_slots" "$project_root/database/migrations/0076_monitor_rule_slots.sql"
  apply_migration_once "0077_comment_research_voice_read_index" "$project_root/database/migrations/0077_comment_research_voice_read_index.sql"
  apply_migration_once "0078_monitor_rule_owns_its_schedule" "$project_root/database/migrations/0078_monitor_rule_owns_its_schedule.sql"
  apply_migration_once "0079_cross_industry_sample_detail" "$project_root/database/migrations/0079_cross_industry_sample_detail.sql"
  apply_migration_once "0065_account_observation_bootstrap" "$project_root/database/migrations/0065_account_observation_bootstrap.sql"
  apply_migration_once "0080_scheduler_admission_failure_reasons" "$project_root/database/migrations/0080_scheduler_admission_failure_reasons.sql"
  apply_migration_once "0081_comment_research_fingerprint" "$project_root/database/migrations/0081_comment_research_fingerprint.sql"
  apply_migration_once "0082_comment_research_execution_recovery" "$project_root/database/migrations/0082_comment_research_execution_recovery.sql"
  apply_migration_once "0083_comment_research_cross_run_resolution_retry" "$project_root/database/migrations/0083_comment_research_cross_run_resolution_retry.sql"
  apply_migration_once "0084_comment_research_problem_resolution_v2" "$project_root/database/migrations/0084_comment_research_problem_resolution_v2.sql"
  apply_migration_once "0085_comment_research_problem_pair_evaluation" "$project_root/database/migrations/0085_comment_research_problem_pair_evaluation.sql"
  apply_migration_once "0086_comment_research_v2_backlog_recall" "$project_root/database/migrations/0086_comment_research_v2_backlog_recall.sql"
  apply_migration_once "0087_cross_industry_detail_comment_policy" "$project_root/database/migrations/0087_cross_industry_detail_comment_policy.sql"
  apply_migration_once "0088_media_processing_concurrency_policy" "$project_root/database/migrations/0088_media_processing_concurrency_policy.sql"
  apply_migration_once "0089_detail_page_session_replay_safety" "$project_root/database/migrations/0089_detail_page_session_replay_safety.sql"
  apply_migration_once "0090_detail_page_grant_recovery_and_risk_cooldown" "$project_root/database/migrations/0090_detail_page_grant_recovery_and_risk_cooldown.sql"
  apply_migration_once "0091_ocr_content_layering" "$project_root/database/migrations/0091_ocr_content_layering.sql"
  apply_migration_once "0092_detail_page_session_recovery_boundary" "$project_root/database/migrations/0092_detail_page_session_recovery_boundary.sql"
  apply_migration_once "0093_capture_delivery_rejection" "$project_root/database/migrations/0093_capture_delivery_rejection.sql"
  apply_migration_once "0094_corpus_evidence_read_recovery" "$project_root/database/migrations/0094_corpus_evidence_read_recovery.sql"
}

case "$command_name" in
  migrate)
    ensure_env
    database_name="${database_name:-$POSTGRES_DB}"
    migrate
    ;;
  repair-password)
    ensure_env
    database_name="${database_name:-$POSTGRES_DB}"
    if [[ "$database_name" != "$POSTGRES_DB" ]]; then
      echo "repair-password only operates on the configured persistent local development database" >&2
      exit 1
    fi
    repair_password
    ;;
  serve)
    ensure_env
    database_name="${database_name:-$POSTGRES_DB}"
    migrate
    bind_runtime_database_target
    # Build the three binaries once. Launching three concurrent `cargo run` processes can make
    # startup appear hung while they contend for Cargo's build lock.
    cargo build -p linggan-api -p linggan-worker --bins
    runtime_drain_dir="$(mktemp -d "${TMPDIR:-/tmp}/linggan-runtime-drain.XXXXXX")"
    export LINGGAN_WORKER_DRAIN_ACK_PATH="$runtime_drain_dir/worker-drain-ack"
    "$project_root/target/debug/linggan-worker" &
    scheduler_pid=$!
    "$project_root/target/debug/linggan-media-worker" &
    media_worker_pid=$!
    "$project_root/target/debug/linggan-api" &
    api_pid=$!
    cleanup_runtime_children() {
      trap - EXIT INT TERM
      kill -TERM "$scheduler_pid" 2>/dev/null || true
      local deadline=$((SECONDS + 90)) ack_pid="" ack_state=""
      while (( SECONDS < deadline )); do
        if [[ -f "$LINGGAN_WORKER_DRAIN_ACK_PATH" ]]; then
          ack_pid="$(awk -F= '$1 == "pid" { print $2; exit }' "$LINGGAN_WORKER_DRAIN_ACK_PATH")"
          ack_state="$(awk -F= '$1 == "state" { print $2; exit }' "$LINGGAN_WORKER_DRAIN_ACK_PATH")"
          if [[ "$ack_pid" == "$scheduler_pid" && "$ack_state" == "drained" ]]; then
            wait "$scheduler_pid" 2>/dev/null || true
            kill "$media_worker_pid" "$api_pid" 2>/dev/null || true
            wait "$media_worker_pid" "$api_pid" 2>/dev/null || true
            rm -f -- "$LINGGAN_WORKER_DRAIN_ACK_PATH"
            rmdir "$runtime_drain_dir"
            return 0
          fi
          [[ "$ack_pid" == "$scheduler_pid" && "$ack_state" != "drained" ]] && break
        fi
        sleep 1
      done
      echo "worker 未确认安全落账；保留其他服务及 drain 回执，不继续强制停止。" >&2
      return 1
    }
    trap cleanup_runtime_children EXIT
    trap 'exit 143' INT TERM
    wait "$api_pid"
    ;;
  *)
    usage
    exit 1
    ;;
esac
