#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$project_root"

usage() {
  cat >&2 <<'EOF'
usage: ./scripts/local-runtime.sh {migrate|repair-password|serve} [--database database_name]

  migrate          apply the three approved local Linggan migrations exactly once
  repair-password  explicitly align the local persistent database role with .env
  serve            migrate the default local database, then start the loopback API

The optional --database form is reserved for an exact, disposable runtime proof
database. It refuses every name except linggan_intelligence_runtime_proof_<hex>.
EOF
}

ensure_env() {
  "$project_root/scripts/setup-local-env.sh" >/dev/null
  set -a
  # shellcheck disable=SC1091
  source "$project_root/.env"
  set +a

  if [[ "${POSTGRES_PASSWORD:-}" == replace-* || "${#POSTGRES_PASSWORD}" -lt 24 ]]; then
    echo "POSTGRES_PASSWORD must be a non-placeholder local secret with at least 24 characters" >&2
    exit 1
  fi

  if [[ "${POSTGRES_USER:-}" != "linggan_dev_admin" || -z "${POSTGRES_DB:-}" ]]; then
    echo "local environment must use linggan_dev_admin and POSTGRES_DB" >&2
    exit 1
  fi

  if [[ ! "${POSTGRES_PORT:-}" =~ ^[1-9][0-9]{0,4}$ ]] || (( POSTGRES_PORT > 65535 )); then
    echo "POSTGRES_PORT must be a valid local TCP port" >&2
    exit 1
  fi
}

database_name=""
if [[ "${1:-}" == "--database" ]]; then
  database_name="${2:-}"
  shift 2
  if [[ ! "$database_name" =~ ^linggan_intelligence_runtime_proof_[0-9a-f]+$ ]]; then
    echo "--database only accepts an exact disposable runtime proof database name" >&2
    exit 1
  fi
fi

if [[ $# -ne 1 ]]; then
  usage
  exit 1
fi
command_name="$1"

psql_in_container() {
  docker compose exec -T postgres psql -X -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$database_name" "$@"
}

local_database_url() {
  # POSTGRES_PASSWORD is generated as hex and POSTGRES_USER is fixed, so neither needs URL
  # escaping. This is intentionally derived from the exact Compose target; DATABASE_ADMIN_URL
  # is not an authority for the runtime target and must never redirect the API after migration.
  printf 'postgresql://%s:%s@127.0.0.1:%s/%s' \
    "$POSTGRES_USER" "$POSTGRES_PASSWORD" "$POSTGRES_PORT" "$database_name"
}

bind_runtime_database_target() {
  local derived_url
  derived_url="$(local_database_url)"
  if [[ -n "${LINGGAN_LOCAL_DATABASE_URL:-}" && "$LINGGAN_LOCAL_DATABASE_URL" != "$derived_url" ]]; then
    echo "LINGGAN_LOCAL_DATABASE_URL conflicts with the exact database verified by migration; refusing to start" >&2
    exit 1
  fi
  export LINGGAN_LOCAL_DATABASE_URL="$derived_url"
}

verify_runtime_port_binding() {
  local published_address
  published_address="$(docker compose port postgres 5432)"
  if [[ "$published_address" != "127.0.0.1:${POSTGRES_PORT}" ]]; then
    echo "the Compose PostgreSQL port does not match the local runtime target; refusing to continue" >&2
    exit 1
  fi
}

verify_application_database_credentials() {
  # The database container's loopback hba rule is trust-based. Verify through
  # a separate Compose client on the database network instead, so this proves
  # the password works for the application connection path. The current .env
  # secret travels only on stdin: it must never become a Docker CLI argument.
  if ! printf '%s\n' "$POSTGRES_PASSWORD" | docker compose run --rm --no-deps -T postgres \
    sh -ceu '
      IFS= read -r database_password
      case "$database_password" in
        ""|*[!0-9a-f]*)
          echo "POSTGRES_PASSWORD must be the hex local secret generated by setup-local-env.sh" >&2
          exit 1
          ;;
      esac
      PGPASSWORD="$database_password" exec psql -X -v ON_ERROR_STOP=1 -h postgres \
        -U linggan_dev_admin -d "$1" -c "SELECT 1;"
    ' sh "$database_name" >/dev/null; then
    echo "the local database role does not accept the current .env password; no data was changed" >&2
    echo "run ./scripts/local-runtime.sh repair-password to explicitly align this local-only role, then retry" >&2
    exit 1
  fi
}

repair_password() {
  "$project_root/scripts/dev-db.sh" up >/dev/null
  # The container may have been created with an older secret. Pass the value
  # just verified from this invocation's .env over stdin; never select the
  # container's startup environment as the repair authority or place it in a
  # Docker CLI argument.
  printf '%s\n' "$POSTGRES_PASSWORD" | docker compose exec -T postgres sh -ceu '
    IFS= read -r repair_password
    case "$repair_password" in
      ""|*[!0-9a-f]*)
        echo "POSTGRES_PASSWORD must be the hex local secret generated by setup-local-env.sh" >&2
        exit 1
        ;;
    esac
    printf "ALTER ROLE linggan_dev_admin PASSWORD '\''%s'\'';\\n" "$repair_password" \
      | psql -X -v ON_ERROR_STOP=1 -U linggan_dev_admin -d postgres >/dev/null
  '
  verify_application_database_credentials
  echo "local database role password aligned with the existing .env; persisted data was not reset or removed"
}

ensure_migration_ledger() {
  docker compose exec -T postgres psql -X -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$database_name" >/dev/null <<'SQL'
    CREATE TABLE IF NOT EXISTS linggan_local_schema_migration (
      migration_id text PRIMARY KEY,
      migration_sha256 text NOT NULL CHECK (migration_sha256 ~ '^[0-9a-f]{64}$'),
      applied_at timestamptz NOT NULL DEFAULT clock_timestamp()
    );
SQL
}

apply_migration_once() {
  local migration_id="$1"
  local migration_path="$2"
  local expected_hash existing_hash
  expected_hash="$(shasum -a 256 "$migration_path" | awk '{print $1}')"
  existing_hash="$(psql_in_container -At -c "SELECT migration_sha256 FROM linggan_local_schema_migration WHERE migration_id = '${migration_id}'")"

  if [[ -n "$existing_hash" ]]; then
    if [[ "$existing_hash" != "$expected_hash" ]]; then
      echo "migration ${migration_id} was previously applied with a different checksum; refusing to continue" >&2
      exit 1
    fi
    echo "migration ${migration_id} already recorded"
    return
  fi

  {
    printf 'BEGIN;\n'
    cat "$migration_path"
    printf "INSERT INTO linggan_local_schema_migration (migration_id, migration_sha256) VALUES ('%s', '%s');\n" "$migration_id" "$expected_hash"
    printf 'COMMIT;\n'
  } | psql_in_container >/dev/null
  echo "migration ${migration_id} applied"
}

migrate() {
  "$project_root/scripts/dev-db.sh" up >/dev/null
  verify_runtime_port_binding
  verify_application_database_credentials
  ensure_migration_ledger
  apply_migration_once "0001_scope_001_capture_evidence" "$project_root/database/migrations/0001_scope_001_capture_evidence.sql"
  apply_migration_once "0002_local_001_discovery" "$project_root/database/migrations/0002_local_001_discovery.sql"
  apply_migration_once "0003_local_trusted_producer" "$project_root/database/migrations/0003_local_trusted_producer.sql"
  apply_migration_once "0004_plugin_runtime_all_capabilities" "$project_root/database/migrations/0004_plugin_runtime_all_capabilities.sql"
  apply_migration_once "0005_collection_observation_target" "$project_root/database/migrations/0005_collection_observation_target.sql"
  apply_migration_once "0006_collection_acquisition_chain" "$project_root/database/migrations/0006_collection_acquisition_chain.sql"
  apply_migration_once "0007_execution_station" "$project_root/database/migrations/0007_execution_station.sql"
  apply_migration_once "0008_collection_risk_pause" "$project_root/database/migrations/0008_collection_risk_pause.sql"
  apply_migration_once "0009_work_order_station" "$project_root/database/migrations/0009_work_order_station.sql"
  apply_migration_once "0010_work_order_lease" "$project_root/database/migrations/0010_work_order_lease.sql"
  apply_migration_once "0011_execution_gate" "$project_root/database/migrations/0011_execution_gate.sql"
  apply_migration_once "0012_target_monitor_schedule" "$project_root/database/migrations/0012_target_monitor_schedule.sql"
  apply_migration_once "0013_drop_execution_gate" "$project_root/database/migrations/0013_drop_execution_gate.sql"
  apply_migration_once "0014_target_group" "$project_root/database/migrations/0014_target_group.sql"
  apply_migration_once "0015_material_projection" "$project_root/database/migrations/0015_material_projection.sql"
  apply_migration_once "0016_material_social_lanes" "$project_root/database/migrations/0016_material_social_lanes.sql"
  apply_migration_once "0017_material_media_projection" "$project_root/database/migrations/0017_material_media_projection.sql"
  apply_migration_once "0018_material_discovery_lane" "$project_root/database/migrations/0018_material_discovery_lane.sql"
}

case "$command_name" in
  migrate)
    ensure_env
    database_name="${database_name:-$POSTGRES_DB}"
    migrate
    ;;
  repair-password)
    ensure_env
    database_name="${database_name:-$POSTGRES_DB}"
    if [[ "$database_name" != "$POSTGRES_DB" ]]; then
      echo "repair-password only operates on the configured persistent local development database" >&2
      exit 1
    fi
    repair_password
    ;;
  serve)
    ensure_env
    database_name="${database_name:-$POSTGRES_DB}"
    migrate
    bind_runtime_database_target
    exec cargo run -p linggan-api
    ;;
  *)
    usage
    exit 1
    ;;
esac
